operating_mode: 1
pipeline:
  brightness: 6
  clahe_clip_limit: 2.0
  confidence_threshold: 0.5
  contrast: 0
  enable_otsu: false
  iou_threshold: 0.3
video:
  input_fps: 30
  processing_fps_limit: 30
  resolution: !!python/tuple
  - 1920
  - 1080
  source: default
zones:
  count_line: null
  define_zone: []
  roi: []
